services:
  datascience-notebook:
      image: jupyter/datascience-notebook:latest
      volumes:
        - D:\source\algo-trading
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container