version: "3"
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      volumes:
        - D:\source\algo-trading
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container